"""Initial migration

Revision ID: b34f0d9e39ff
Revises: 
Create Date: 2025-05-30 15:01:18.034452

"""
from alembic import op
import sqlalchemy as sa


# Identificadores de revisão usados pelo Alembic.
revision = 'b34f0d9e39ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###